### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/community-data-files#139]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_payment_unece - By @bealdav - #147
- [x] account_tax_unece - By @syera94 - #146
- [x] base_bank_from_iban - By @pegonzalezspesol / @pedrobaeza - #141
- [x] base_currency_iso_4217 - By @BT-anieto - #171
- [x] base_iso3166 - By @ramiadavid - #143
- [x] base_unece - By @syera94 - #142
- [ ] company_sanitary_registry - By @CarlosRoca13 - #167
- [x] product_fao_fishing - By @stefan-tecnativa - #162
- [x] uom_unece - By @marielejeune - #140

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by pegonzalezspesol** [comment]
working on base_bank_from_iban

**Comment by ramiadavid** [comment]
Hi @sbidoul 

im working in `base_iso3166` #143

**Comment by pedroguirao** [comment]
Working on l10n_eu_nace

**Comment by pedroguirao** [comment]
pedroguirao:16.0-mig-l10n_eu_nace #163

**Comment by astirpe** [comment]
All the modules in the list were migrated, so this issue could be closed

**Comment by BT-anieto** [comment]
I'm missing the module **base_currency_iso_4217**

**Comment by BT-anieto** [comment]
Standart migration of base_currency_iso_4217 in #171
