### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/community-data-files#16]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] base_iso3166 - By @etobella - #25 
- [x] base_unece - By @alexis-via - #17 
- [x] account_payment_unece - By @alexis-via - #17 
- [x] account_tax_unece - By @alexis-via - #17 
- [x] l10n_eu_nace - By @mayjo79 - #18 
- [x] product_uom_unece - By @alexis-via - #17
