### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/community-data-files#28]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_payment_unece - By @astirpe - #36 
- [x] account_tax_unece - By @astirpe - #34 
- [x] base_iso3166 - By @etobella - #29 
- [x] base_unece - By @astirpe - #33 
- [ ] l10n_eu_nace - By @oihane - #39
- [x] product_uom_unece - By @astirpe - #35

**Comment by astirpe** [comment]
base_unece https://github.com/OCA/community-data-files/pull/33

**Comment by astirpe** [comment]
account_tax_unece https://github.com/OCA/community-data-files/pull/34

**Comment by astirpe** [comment]
product_uom_unece: #35

**Comment by astirpe** [comment]
account_payment_unece: #36

**Comment by emagdalenaC2i** [comment]
There is a PR for the migration of l10n_eu_nace - By @oihane - #39
