### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/community-data-files#6]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_tax_unece - By @hbrunn - #20 
- [ ] base_iso3166
- [x] base_unece - By @hbrunn - #20 
- [x] l10n_eu_nace
- [x] product_uom_unece - By @hbrunn - #20

**Comment by KaloyanNaumov** [comment]
base_iso3166 seems to be working fine with v9 currently. 

What kind of help is needed? If I may assist?

**Comment by pedrobaeza** [comment]
You can propose a PR with the module. Some references:
- https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
- https://odoo-community.org/page/code

**Comment by pedrobaeza** [comment]
Closing as base_iso3166 is not going to be migrated.
